timezone: Europe/Moscow
name: 'Прозрачная ортодонтия 3.0'
descr: 'Прозрачная ортодонтия состоит из двух семинаров, которые пройдут 17 - 18 ноября 2017.'
markdown: redcarpet
email: 'hello@dentalagency.ru'
phone: '+7 (985) 600 49 49'
